encoding: utf-8

plugins:
  - jekyll-regex-replace

# Site identity
title: shanks//lab
description: Minimal hacker notes, writeups, and experiments.
keywords: cybersecurity, pentest, red team, writeups
author: shanks
footerText: shanks//lab

permalink: /posts/:year/:month/:day/:title.html
kramdown:
  auto_ids: true
  input: GFM
  syntax_highlighter: rouge
exclude: [vendor]

# Project Pages settings
domainUrl: 'https://shanksfigarland.github.io'
baseurl: '/shanks.github.io'

tucaoUrl:

menu:
  - title: home
    url: /
  - title: archive
    url: /pages/categories.html
  - title: search
    url: /pages/search.html
  - title: about
    url: /pages/about.html

extClickEffect: false
extAdsense: false
extMath: false
extCount: false
